name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          USERNAME: hacketthadwin
          TRANSPARENT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: ./profile-3d-contrib/profile-transparent.svg

      - name: Ensure Transparent Background
        run: |
          python -c "
          import xml.etree.ElementTree as ET
          svg_file = './profile-3d-contrib/profile-transparent.svg'
          tree = ET.parse(svg_file)
          root = tree.getroot()
          # Remove background rect or set fill to none
          for rect in root.findall('.//{http://www.w3.org/2000/svg}rect[@class=\"fill-bg\"]'):
              rect.set('fill', 'none')
          # Ensure SVG has transparent style
          root.set('style', 'background: transparent;')
          tree.write(svg_file, encoding='utf-8', xml_declaration=True)
          "

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add 3D contribution graph with transparent background"
          git push
