name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          USERNAME: hacketthadwin
          TRANSPARENT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: ./profile-3d-contrib/profile-transparent.svg

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add 3D contribution graph"
          git push
