name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch: # Run manually anytime
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ./profile-3d-contrib

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          USERNAME: hacketthadwin
          TRANSPARENT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_dir: ./profile-3d-contrib

      - name: Wait for file generation
        run: sleep 5

      - name: Check if file exists
        run: |
          if [ -f "./profile-3d-contrib/profile-night-green.svg" ]; then
            echo "File found."
          else
            echo "File not found."
            exit 1
          fi

      - name: Make background transparent
        run: |
          python -c "
with open('./profile-3d-contrib/profile-night-green.svg', 'r') as file:
    content = file.read()
content = content.replace('.fill-bg { fill: #00000f; }', '.fill-bg { fill: transparent; }')
content = content.replace('.stroke-bg { stroke: #00000f; }', '.stroke-bg { stroke: transparent; }')
with open('./profile-3d-contrib/profile-night-green.svg', 'w') as file:
    file.write(content)
          "
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update 3D contribution graph with transparent background"
          git push
