name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch: # Run manually anytime
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ./profile-3d-contrib

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          USERNAME: hacketthadwin
          TRANSPARENT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_dir: ./profile-3d-contrib
